repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.6
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args:
          [
            "-rn",
            "-sn",
            "--rcfile=pyproject.toml",
          ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
    -   id: mypy
        args: [--ignore-missing-imports]
        additional_dependencies: [
          types-requests==2.32.0.20241016,
          types-pyyaml==6.0.12.20241230,
          types-dateparser==1.2.0.20250208,
          types-tabulate==0.9.0.20241207
        ]
